config/routes.rb
CaseBlurb::Application.routes.draw do
  resources :cases do
    resources :blurbs, only: :create
    resources :docs
  end

  resources :users, except: :show

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root to: 'home#index'

end

app/models/blurb.rb
class Blurb < ActiveRecord::Base
  attr_accessible :content, :case_id, :user_id
  belongs_to :case
  belongs_to :user
  validates :case_id, :user_id, presence: true
end

app/models/case.rb
class Case < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :users
  has_many :docs, dependent: :destroy
  has_many :blurbs, dependent: :destroy

  validates :name, presence: true
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  attr_accessible :name

  belongs_to :case

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation

  has_secure_password

  has_and_belongs_to_many :cases

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery

  protected
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: 'Please log in'
      end
    end
end

app/controllers/blurbs_controller.rb
class BlurbsController < ApplicationController
	# /cases/:case_id/blurbs(.:format)
  def create
    @case = Case.find(params[:case_id])
    @blurb = @case.blurbs.create(params[:blurb])
    redirect_to case_path(@case)
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  def index
    @cases = Case.all
  end

  def new
    @case = Case.new
  end

  def edit
    @case = Case.find(params[:id])
  end

  def show
    @case = Case.find(params[:id])
  end

  def create
    @case = Case.new(params[:case])

    if @case.save
      redirect_to @case, notice: 'Case successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @case = Case.find(params[:id])

    if @case.update_attributes(params[:case])
      redirect_to @case, notice: 'Case successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @case = Case.find(params[:id])
    @case.destroy

    redirect_to cases_url
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_filter :find_case
  skip_before_filter :authorize

  def index
    @docs = @case.docs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @docs }
    end
  end

  def show
    @doc = @case.docs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doc }
    end
  end

  def new
    @doc = @case.docs.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doc }
    end
  end

  def edit
    @doc = @case.docs.find(params[:id])
  end

  def create
    @doc = @case.docs.build(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to case_doc_path(@case, @doc), notice: 'Doc was successfully created.' }
        format.json { render json: @doc, status: :created, location: @doc }
      else
        format.html { render action: "new" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @doc = @case.docs.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to case_doc_path(@case, @doc), notice: 'Doc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to case_docs_url }
      format.json { head :no_content }
    end
  end

  protected
    def find_case
      @case = Case.find(params[:case_id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_name] = user.username
      redirect_to root_url
    else
      redirect_to login_url, alert: "Invalid stuff!"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:user_name] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blurbs_helper.rb
module BlurbsHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cases/_form.html.erb
<%= form_for(@case) do |f| %>
  <% if @case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
      <% @case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
<h1>Edit Case</h1>

<%= render 'form' %>

<%= link_to 'Back', cases_path %>

app/views/cases/index.html.erb
<div>
  <div class="well">
    <table class="table">
      <thead>
        <tr>
          <th>Case Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cases.each do |c| %>
          <tr>
            <td><%= c.name %></td>
            <td>
              <%= link_to 'Detail', c %> |
              <%= link_to 'Edit', edit_case_path(c) %> |
              <%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Case', new_case_path %>
  </div>
</div>

app/views/cases/new.html.erb
<h1>New Case</h1>

<%= render 'form' %>

<%= link_to 'Back', cases_path %>

app/views/cases/show.html.erb
<div class="row-fluid">
  <div class="well">
    <div>
      <h1><%= @case.name %></h1>

      <%= link_to 'Edit', edit_case_path(@case) %> | <%= link_to 'Back', cases_path %>
    </div>
    <div>
      <%= link_to 'Manage Case Documents', case_docs_path(@case) %>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span6">
    <div pub-key="pub-8170e21c-7fd2-4c90-aee1-88261c5c5816" sub-key="sub-894d0468-e416-11e1-a5bd-178bb4b7ab64" ssl="off" origin="pubsub.pubnub.com" id="pubnub"></div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"> </script>
    <script src="http://cdn.pubnub.com/pubnub-3.1.min.js"></script>

    <div class="blurbs-box">
    	<div class="input-box">
    		<textarea class="input-xlarge span6" name="new-message" id="message-field" placeholder="Type new blurb..." rows="3"></textarea>
    	</div>
      <br>
    	<div class="convo-box">
        <% @case.blurbs.order("created_at DESC").each do |b| %>
          <div class="well">
            <div class="row-fluid">
              <span class="message-sender"><%= b.user.username rescue "" %></span>
              <span class="message-date pull-right"><%= b.created_at %></span>
            </div>
            <div class="row-fluid">
              <span class="message-text"><%= b.content %></span>
            </div>
          </div>
        <% end %>
    	</div>
    </div>
  </div>
  <div class="span6">
    <ul>
    <% @case.docs.each do |doc| %>
      <li><%= doc.name %></li>
    <% end %>
    </ul>
  </div>
</div>

<style>
	.message-sender{
		font-weight: bold;
	}
	.message-date{
		font-size: 90%;
		margin-right: 0.5em;
		font-style: italic;
	}
</style>

<script> (function(){
	// Channel to be provided by CaseBlurb db. Probably use case_id.
	var channel = "<%= @case.name %> <%= @case.id %>";
	// Provide username too for posting to convo box:
	var user = "<%= session[:user_name]%>";
	var msgBox = $('#message-field');
 
    // LISTEN FOR MESSAGES
    PUBNUB.subscribe({
        channel    : channel,      // CONNECT TO THIS CHANNEL.
 
        restore    : false,              // STAY CONNECTED, EVEN WHEN BROWSER IS CLOSED
                                         // OR WHEN PAGE CHANGES.
 
        callback   : function(message) { // RECEIVED A MESSAGE.
        	// TODO: Add date/time stamp from rails
            $('.convo-box').prepend('\
        		<div class = "well">\
              <div class="row-fluid">\
        			<span class="message-sender">'+message.sender+'</span>\
        			<span class="message-date pull-right"><%= Time.now %></span>\
              </div>\
              <div class="row-fluid">\
        			<span class="message-text">'+message.text+'</span>\
              </div>\
        		</div>')
        },
 
        disconnect : function() {        // LOST CONNECTION.
            $('.convo-box').prepend(
                "<div class=\"well\">\
                	Error: Connection Lost." +
                	"Will auto-reconnect when Online.\
                </div>"
            )
        },
 
        reconnect  : function() {        // CONNECTION RESTORED.
            $('.convo-box').append("Connection restored!")
        },
 
        connect    : function() {        // CONNECTION ESTABLISHED.		            
            PUBNUB.publish({             // SEND A MESSAGE.
                channel : channel,
                message : {sender: '[Announcement]', text: user + " is now viewing this blurb.", date: '[date]'}
            })
        }
    });
	$('#message-field').keyup(function(e) {
		if((e.which) === 13){
			PUBNUB.publish({
				channel : channel, 
				message : {sender: user,
					text: msgBox.val(),
					date:'[date]'
				},
				callback: function(resp){
					$.ajax({
						url: '<%= @case.id %>/blurbs.json',
						type:'POST',
						data:{blurb:{content:msgBox.val(),
							user_id:<%= session[:user_id] %>}
						}
					})
					msgBox.val('');
				}
			});
		}
	});
})();
</script>

app/views/docs/_form.html.erb
<%= form_for([@case, @doc]) do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', case_doc_path(@case, @doc) %> |
<%= link_to 'Back', case_docs_path %>

app/views/docs/index.html.erb
<h1>Listing docs</h1>

<ul>
  <% @docs.each do |doc| %>
    <li>
      <%= doc.name %> | 
      <%= link_to 'Show', case_doc_path(@case, doc) %> | 
      <%= link_to 'Edit', edit_case_doc_path(@case, doc) %> | 
      <%= link_to 'Destroy', case_doc_path(@case, doc), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<br />

<%= link_to 'New Doc', new_case_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', case_docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @doc.name %></h1>

<%= link_to 'Edit', edit_case_doc_path(@case, @doc) %> |
<%= link_to 'Back', case_docs_path %>

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>LegalFile</h1>
  <p>Html9ResponsiveBoilerStrapJs Edition<br>
  Improved with CaseBlurb!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CaseBlurb" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to 'LegalFile', root_path, class: "brand" %>
          
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i>
              <% if session[:user_id] %>
                <%= session[:user_name] %>
              <% else %>
                Username
              <% end %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </div>
          
          <div class="container-fluid nav-collapse">
          <% if session[:user_id] %>
            <ul class="nav">
              <li><%= link_to 'Cases', cases_path  %></li>
            </ul>
          <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        
        <%= yield %>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm' %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<% if notice %>
  <p><%= notice %></p>
<% end %>

<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td>
      <%= link_to 'Edit', edit_user_path(user) %><br>
      <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>